## General Configuration for application
spring.application.name=${APPLICATION_NAME}
server.port=${PORT}
environment=${ENVIRONMENT}


## Amazon SQS configuration
amazon.aws.accessKey=${AWS_ACCESS_KEY_ID}
amazon.aws.secretKey=${AWS_SECRET_ACCESS_KEY}
amazon.aws.region=${AWS_REGION}
amazon.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}