## General Configuration for application
spring.application.name=${APPLICATION_NAME:aws-sqs}
server.port=${PORT:8081}
environment=${ENVIRONMENT:local}


## Amazon SQS configuration
amazon.aws.accessKey=${AWS_ACCESS_KEY_ID:test}
amazon.aws.secretKey=${AWS_SECRET_ACCESS_KEY:test}
amazon.aws.region=${AWS_REGION:us-east-1}
amazon.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}